var browserify = require('browserify');
var b = browserify();
b.require('events');
b.require('stream');
b.require('buffer');
b.require('http');
b.require('zlib');
b.require('http-parser-js');
b.require('js-base64');
b.add('./app.js');
b.bundle().pipe(process.stdout);